routes/web.php
<?php

//login
use App\HistorialClinico;
use App\Resultados;
use App\User;
// use Illuminate\Routing\Route;

Auth::routes(['register' => false]);
Route::get('/', function () {
    if (Auth::user()) {
        return redirect()->action('RoleController@index');
    } else {
        return view('auth/login');
    }
});

// NOTE: eliminar siguiente funcion


// Route::get('resultados_create', function () {
//     $historial = HistorialClinico::all();
//     foreach ($historial as  $value) {
//         $resultado = Resultados::where('hc', $value->id)->first();
//         if ($resultado) {
//             \DB::table('resultados')
//                 ->where('id', $resultado->id)
//                 ->update([
//                     'expediente_id' => $value->expediente_id
//                 ]);
//         }
//     }
//     return "true";
// });

Route::post('validar_email', function () {
    $validacion = false;
    $user  = User::where('email', $_POST['email'])->first();
    if ($user == null) {
        $validacion = true;
    }
    return response()->json($validacion, 200);
});

Route::post('users/{id}', function ($id) {
});






// NOTE: HTDS
Route::get('/loginHtds/{nombre}/{pass}', 'Empresa\HtdsController@authenticate');
// NOTE: Administrador
Route::get('/Administrador', 'RoleController@index')->name('admin');
Route::get('DiagnosticosIndicador', 'Empresa\EmpresasController@indicadores');
Route::post('DiagnosticosDate', 'Empresa\EmpresasController@indicadoresDate');



Route::get('getimage/{filename}', 'RegistroEmpresaController@getImage')->name('getImage');

// Rutas administrador
Route::get('/Registro', 'RegistroEmpresaController@viewRegistro')->name('empresa')->middleware('admin');
Route::post('/registroController', 'RegistroEmpresaController@registro')->name('registro')->middleware('admin');
Route::get('/Contacto', 'RouteController@contacto')->name('contacto')->middleware('admin');
Route::get('/Estudios', 'RouteController@estudios')->name('estudios')->middleware('admin');
Route::get('/Estudios_get/{id}', 'RouteController@getEstudios')->name('getestudios')->middleware('admin');
Route::get('/Estudio/{id}', 'RouteController@getEstudio')->name('getEstudio')->middleware('admin');
Route::post('/updateEstudio', 'Administrador\EstudiosController@updateEstudio')->name('editar_estudio')->middleware('admin');
Route::post('/altaEstudio', 'Administrador\EstudiosController@alta')->name('altaEstudio')->middleware('admin');
Route::get('/Empresas', 'RouteController@verEmpresas')->name('admin-verEmpresas')->middleware('admin');
Route::get('/Empresas/{nombreEmpresa}', 'RouteController@showEmpresa')->name('admin-showEmpresa')->middleware('admin');
Route::post('/actualizar-logo', 'Administrador\EmpresasController@cambiarLogotipo')->name('cambiarLogotipo')->middleware('admin');
Route::get('/getEstudiosEmpresa/{encryptedID}', 'Administrador\EmpresasController@getEstudiosEmpresa')->name('getEstudiosEmpresa')->middleware('admin');
Route::post('/selectorEstudiosEmpresa', 'Administrador\EmpresasController@selectorEstudiosEmpresa')->name('selectorEstudiosEmpresa')->middleware('admin');
Route::get('Empresas/{nombreEmpresa}/editar-empresa', 'Administrador\EmpresasController@editarEmpresa')->name('editarEmpresa')->middleware('admin');
Route::get('Empresas/{nombreEmpresa}/editar-contacto', 'Administrador\EmpresasController@editarContacto')->name('editarContacto')->middleware('admin');
Route::post('/actualizar-empresa', 'Administrador\EmpresasController@actualizarEmpresa')->name('actualizarEmpresa')->middleware('admin');
Route::post('/actualizar-contacto', 'Administrador\EmpresasController@actualizarContacto')->name('actualizarContacto')->middleware('admin');
Route::get('EmpresaAdmin/{nomEmpresa}', 'RoleController@admin')->name('EmpresaAdmin')->middleware('admin');
Route::get('AdminSalir', 'RoleController@salirAdmin')->name('AdminSalir')->middleware('role');

//Rutas de Empresas

Route::get('/consultasStats/{year}', 'Empresa\EmpresasController@getConsultasStats')
    ->middleware('role');

Route::get('/estudios_get_name', 'Empresa\EstudiosController@estudios')
    ->middleware('role');



Route::get('/Indicadores-Covid', 'Empresa\CovidController@covid_indicadores')->name('covid_indicador')->middleware('role');
Route::get('/get_info_covid', 'Empresa\CovidController@get_empleados_covid')->middleware('role');

//RUTAS DE EMPRESA > RUTAS DE MEDICOS
Route::get('/configuracion-usuarios', 'Empresa\AdminUsuariosController@index')->name('config-usuarios')->middleware('role');
Route::get('/configuracion-usuarios/{user_id}', 'Empresa\AdminUsuariosController@detalle_usuario')->name('config-usuarios-detalle')->middleware('role');

Route::get('/Expediente', 'RouteController@expediente')->name('expediente')->middleware('role');
Route::get('/Empleados', 'Empresa\EmpleadosController@empleados')->name('empleados')->middleware('role');
Route::get('buscarempleados', 'Empresa\EmpleadosController@buscarempleados')
    ->name('buscarempleados')
    ->middleware('role');
Route::get('/ObtenerCalculadoraC/{id}', 'RouteController@covid')->middleware('role');
Route::post('/CalculadoraC', 'RouteController@CalculadoraC')->middleware('role');

Route::get('/VistaEmpr', 'RouteController@vistaEmpresa')->name('VEmpresa')->middleware('role');
Route::get('api/empleados', 'RouteController@getEmpleados')->middleware('role');
Route::get('api/grupos', 'RouteController@getGrupos')->middleware('role');
Route::resource('empleados', 'Empresa\EmpleadosController')->middleware('role');
Route::post('eliminarEmpleado', 'Empresa\EmpleadosController@eliminarEmpleado')->name('eliminarEmpleado')->middleware('role');
Route::resource('grupos', 'Empresa\GruposController')->middleware('role');
Route::post('new_grupo', 'Empresa\GruposController@insertGrupo')->middleware('role');

Route::get('Grupos', 'Empresa\GruposController@index')->name('grupos')->middleware('role');


Route::get('delete_grupo/{nombre}', 'Empresa\GruposController@deleteGrupo')->name('deletegrupo')->middleware('role');

Route::post('updateGrupos', 'Empresa\GruposController@updateGrupo')->middleware('role');

Route::get('grupos/getEmpleadosDeGrupo/{encryptedID}', 'RouteController@getEmpleadosDeGrupo')->middleware('role');
Route::get('/AltaEmpleados', 'RouteController@AltaEmpleado')->name('alta_empleado')->middleware('role');

Route::post('/altaEmpleados', 'Empresa\EmpleadosController@insertEmpleado')->middleware('role');


Route::get('/VerEstudioProgramado', 'RouteController@getEstudioProgramado')->name('ver_programado')->middleware('role');
Route::get('empleados/Empleado/{encryptedID}', 'RouteController@getEmpleado')->name('empleado')->middleware('role');

Route::post('empleados/updateEmpleado', 'Empresa\EmpleadosController@updateEmpleado')->name('updateEmpleado')->middleware('role');

Route::post('/imgeChange', 'Empresa\EmpleadosController@updateImage')
    ->middleware('role');

Route::post('/docPatient', 'Empresa\EmpleadosController@docuementos')
    ->middleware('role');

Route::post('/deleteDoc', 'Empresa\EmpleadosController@deleteArchivo')
    ->middleware('role');

Route::get('empleados/getEstudioProgramado/{id}', 'RouteController@getEstudioProgramado')->name('getEstudioProgramado')
    ->middleware('role');

Route::post('/selectorEstudiosGrupo', 'Empresa\GruposController@selectorEstudiosGrupo')->name('selectorEstudiosGrupo')->middleware('role');
Route::post('/agregarEmpleadosGrupo', 'Empresa\GruposController@agregarEmpleadosGrupo')->name('agregarEmpleadosGrupo')->middleware('role');


Route::post('/programarEstudiosGrupo', 'Empresa\GruposController@programarEstudiosGrupo')->name('programarEstudiosGrupo')->middleware('role');
Route::post('/eliminarEstudioGrupo', 'Empresa\GruposController@eliminarEstudioGrupo')->name('eliminarEstudioGrupo')->middleware('role');
Route::post('/eliminarEstudioEmpleado', 'Empresa\EmpleadosController@eliminarEstudioEmpleado')->name('eliminarEstudioEmpleado')->middleware('role');
Route::post('/programarEstudiosEmpleadoGrupo', 'Empresa\EmpleadosController@programarEstudiosEmpleadoGrupo')->name('programarEstudiosEmpleadoGrupo')->middleware('role');
Route::post('/programarEstudiosEmpleado', 'Empresa\EmpleadosController@programarEstudiosEmpleado')->name('programarEstudiosEmpleado')->middleware('role');
Route::post('/sass_orden', 'Empresa\EmpleadosController@sass_orden');
Route::post('/sass_orden_delete', 'Empresa\EmpleadosController@deleteOrden');
//Route::post('/daicom', 'Empresa\EmpleadosController@daicom');
//Route::get('/daicom', function () {
  //  return view('Empresa.daicom');
//});
Route::get('/daicom', 'Empresa\EmpleadosController@daicom');





// Resultados de Laboratorio

Route::get('/Resultados/{id}/{id_estudio}', 'Empresa\Laboratorio\EstudiosController@tablaestudios')
    ->name('sassResultados')
    ->middleware('role');
Route::get('/ShowEstudio/{id}', 'Empresa\LaboratorioController@showEstudios')->middleware('role');
Route::get('/Resultados', 'Empresa\ResultadosController@index')->name('resultados')->middleware('role');
Route::get('/Resultados1/{fecha_inicial}/{fecha_final}', 'Empresa\ResultadosController@estudios_fech');
Route::get('/Archivos/{id}', 'Empresa\ResultadosController@archivo')->name('archivo')->middleware('role');
Route::get('/grupos/getEstudiosProgramadosGrupo/{nombre}', 'RouteController@getEstudiosProgramadosGrupo')->name('getEstudiosProgramadosGrupo')->middleware('role');
Route::get('/grupos/getEstudiosProgramadosEmpleado/{curp}', 'RouteController@getEstudiosProgramadosEmpleado')->name('grupos.getEstudiosProgramadosEmpleado')->middleware('role');
Route::get('getEmpleadosSinGrupo', 'RouteController@getEmpleadosSinGrupo')->name('getEmpleadosSinGrupo')->middleware('role');
Route::get('/empleados/getEstudiosProgramadosEmpleado/{curp}', 'RouteController@getEstudiosProgramadosEmpleado')->name('empleados.getEstudiosProgramadosEmpleado')->middleware('role');
Route::get('/indicadores', 'RouteController@vistaIndicadores')->name('vistaIndicadores')->middleware('role');

app/Http/Controllers/Empresa/AccesosController.php
<?php

namespace App\Http\Controllers\Empresa;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

use App\Roles;
use App\Accesos;
use App\Modulos;
use App\Crud;
use App\User;

class AccesosController extends Controller {
  public function index(){
    $roles = $this->roles();
    $modulos = $this->modulos();
    $cruds = $this->crud();
    return view('Empresa/accesos/accesos',compact('roles','modulos','cruds'));
  }

  public function roles(){
    return Roles::where('empresa_id',Session::get('empresa')->id)->get();
  }
  public function modulos(){
    return Modulos::all();
  }

  public function crud(){
    return Crud::all();
  }

  public function permisos($id){
    return Accesos::select('c.nombre as crud', 'm.nombre as modulo','roles.tipo','accesos.id')
    ->where('rol_id',$id)
    ->join('roles','roles.id','accesos.rol_id')
    ->join('crud as c','c.id','accesos.crud_id')
    ->join('modulos as m','m.id','accesos.modulo_id')
    ->get();
  }

  public function deleteAcc(Request $data){
    try {
      \DB::beginTransaction();
        $ac = Accesos::find($data->id);
        $ac->delete();
      \DB::commit();
      $data = array(
        'status' => 200 ,
        'message'=> 'succes',
        'data' =>$ac
      );
    } catch (\Exception $e) {
      $data = array(
        'status' => 401 ,
        'message'=> 'error'
      );
    }
    return response()->json($data,$data['status']);

  }

    public function addPermiso(Request $data){
            $rol_id = $data->role;
            $modulo_id = $data->modulo;
            $crud_id = $data->operacion;
            // $permiso = Accesos::where([
            //   ['rol_id', $rol_id],
            //   ['modulo_id' ,$modulo_id],
            //   ['crud_id' ,$crud_id]
            // ])
            // ->first();
            // if (!$permiso) {7
            $validador = false;
            foreach ($data->operacion as $key => $value) {
                $permiso = Accesos::where('rol_id',$rol_id)->where('modulo_id',$modulo_id)->where('crud_id',$value)->first();
                if($permiso == null)
                {
                    try {
                        \DB::beginTransaction();
                        $acc = new Accesos();
                        $acc->rol_id = $rol_id;
                        $acc->modulo_id = $modulo_id;
                        $acc->crud_id = $value;
                        $acc->save();
                        \DB::commit();
                        $data = array(
                        'status' => 200,
                        'message'=>'success',
                        'data'=>$acc
                        );
                        $validador = true;
                    } catch (\Exception $e) {
                        DB::rollback();
                        dd($e);
                        $data = array(
                        'statu' => 401,
                        'message' =>'error',
                        'data' => $e
                        );
                    }
                }
            }
            if($validador)
            {
                return response()->json($data,$data['status']);
            }else{
                $data = array('status' => 200,'message' => 'repeat','data' => 'repeat');
                return response()->json($data, 200);
            }
    }

  public function addRol(Request $data){
    try {
      $roles = $data->rol;
      $description = $data->description;
      \DB::beginTransaction();
        $rol = new Roles();
        $rol->tipo = $roles;
        $rol->descripcion = $description;
        $rol->empresa_id = \Session::get('empresa')->id;
        $rol->save();
      \DB::commit();
      $data = array(
        'statu' => 200,
        'message'=>'success',
        'data'=>$rol
      );
    } catch (\Throwable $e) {
      $data = array(
        'statu' => 401,
        'message' =>'error',
        'data' => $e
      );
    }
    return response()->json($data,$data['statu']);
  }

  public function addRolDelete(Request $data){

   $rol = $data->id;
   $user = User::where('role_id',$rol)->first();

   if (!$user) {
       try {
         \DB::beginTransaction();
         $rols =  Roles::find($rol);
         $rols->delete();
         Accesos::where('rol_id',$rol)->delete();
         \DB::commit();
         $data = array(
           'statu' => 200,
           'message'=>'success',
           'data'=>$rols
         );
       } catch (\Throwable $e) {
         dd($e);
         $data = array(
           'statu' => 401,
           'message' =>'error',
           'data' => $e
         );
     }
   }else {
     $data = array(
       'statu' => 403,
       'message' =>'hay usuarios con ese rol',
       'data' =>'user'
     );
   }
   return response()->json($data,$data['statu']);

 }

}

app/Http/Controllers/Empresa/ChatController.php
<?php

namespace App\Http\Controllers\Empresa;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Mail;

use App\Mail\MailUsuarioSecundario;
use App\User;
use App\Empresa;
use App\Empleado;
use App\Covid;
use App\SassOrden;

class ChatController extends Controller {
  use AuthenticatesUsers;

  public function index()
  {
    return view('Empresa/chat/chat');
  }
}

app/Http/Controllers/Empresa/EstudiosController.php
<?php
namespace App\Http\Controllers\Empresa;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use DB;
use App\Empresa;
use App\Empleado;
use App\EstudioProgramado;
use App\Grupo;
use App\Categoria;
use App\Estudios;


class EstudiosController extends Controller
{
    public function estudios(Request $request){
        $term = $request->get('term');
        return Estudios::where('nombre','like', '%'.$term.'%')
        ->get();
    }
}

app/Http/Controllers/Empresa/EstudiosProgramadosController.php
<?php

namespace App\Http\Controllers\Empresa;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\EstudioProgramado;
use App\Categoria;
use App\Estudio;
use App\Empleado;

class EstudiosProgramadosController extends Controller
{   
    /*
    |--------------------------------------------------------------------------
    | Controlador de todas las operaciones del modelo EstudioProgramado
    |--------------------------------------------------------------------------
    |
    | Permite la administración de vistas y APIs que involucren
    | datos de un estudio programado.
    |
    */

    /**
     * Obtener un estudio programado
     * 
     * Devuelve toda la información del estudio programado cuyo ID
     * coincida con el ID recibido como parámetro
     * 
     * @param Integer ID del estudio programado por devolver
     * @return json Datos del estudio programado
     */
    function getEstudioProgramado($id) {
        $estudio_programado = EstudioProgramado::where('id', $id)->first();
        return json_encode($estudio_programado);
    }
    function estudiospro(){
        $estudio_programado = EstudioProgramado::all();    
        return view('Empresa.Resultados')->with(json_encode($estudio_programado));    
    }
 
      
       
   
}

resources/views/Empresa/empleado/medicamentosactivos.blade.php
@extends('layouts.Vuexy')
@section('title','Historial Medicamentos')
@section('begin_vendor_css')
<link rel="stylesheet" type="text/css"
    href=" {!! asset('public/vuexy/app-assets/vendors/css/tables/datatable/datatables.min.css') !!}">
<link rel="stylesheet" type="text/css"
    href=" {!! asset('public/vuexy/app-assets/vendors/css/file-uploaders/dropzone.min.css') !!}">

@endsection
@section('page_css')
<link rel="stylesheet" type="text/css" href=" {!! asset('public/css/daicoms/daicoms.css') !!}">
<link rel="stylesheet" type="text/css"
    href=" {!! asset('public/vuexy/app-assets/css/plugins/file-uploaders/dropzone.min.css') !!}">
<link rel="stylesheet" type="text/css"
    href=" {!! asset('public/vuexy/app-assets/css/pages/data-list-view.min.css') !!}">
@section('css_custom')
<link rel="stylesheet" href="{!! asset('public/css/empresa/pacientes.css') !!}">
<link rel="stylesheet" type="text/css"
    href=" {!! asset('public/vuexy/app-assets/css/plugins/file-uploaders/dropzone.min.css') !!}">

@endsection
@section('content')
<nav aria-label="breadcrumb">

    <ol class="breadcrumb breadcrumb-chevron">
        <li class="breadcrumb-item"><a href="{{ route('empleados') }}">Empleados</a></li>

        <li class="breadcrumb-item"><a href="{{ route('empleados.show', $empleado->CURP)}}">{{$empleado->nombre}} {{$empleado->apellido_paterno}} {{$empleado->apellido_materno}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Historial de Medicamentos</li>
    </ol>


   
</nav>
<div class='row'>
 
  <div class='col-md-6'>
    <div class="card" id="medicamentos">
        <div class="card-header bg-secondary" style="padding: .6rem !important;">
            <h6 class="card-title font-weight-light text-white">Medicamentos</h6>
        </div>
        <div class="card-content collapse show" style="">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-12 mb-1">
                        <input type="text" class="form-control search input-sm" placeholder="Buscar Medicamentos">
                    </div>
                    <div class="col-md-12 list">
                      @forelse($empleado->expediente->consultas as $consulta)
                        @foreach($consulta->medicamentos as $medicamento)
                        <div class="twitter-feed">
                            <div class="d-flex justify-content-start align-items-center">
                                    <div class="col-md-12">
                                        <small class="badge bg-secondary mb-1 fecha">{{ \Carbon::parse($medicamento->created_at)->format('M / d / Y') }}</small>
                                        <h6 class="text-bold-600 mb-0 text-center primary nombre">{{ $medicamento->nombre }}</h6>
                                      
                                        <h6 class="d-block line-ellipsis text-center frecuencia"><b class='secondary'>Tomar:</b> {{ $medicamento->frecuencia }}</h6>
                                        <h6 class="d-block line-ellipsis text-center duracion"><b class='secondary'>Durante:</b> {{ $medicamento->duracion }}</h6>
                                        <h6 class="d-block  line-ellipsis text-center comentario"><b class='secondary'>Comentarios:</b> {{ $medicamento->comentario }}</h6>
                                    </div>
                                
                            </div>
                            <hr>
                        </div>
                        @endforeach
                        @empty
                    <div class="alert">
                        <div class="alert alert-danger">
                            No hay Medicamentos
                        </div>
                     </div>
                    @endforelse
                    </div>

                    <div class="col-md-12 mt-1">
                        <div class="d-flex align-items-center justify-content-center">
                            <div id="anterior"></div>
                            <ul class="pagination justify-content-center m-0"></ul>
                            <div id="siguiente"></div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
  </div>
  <div class='col-md-6'>
    <div class="card">
      <div class="card-header bg-secondary">
                <h4 class="text-white text-center">Indicadores</h4>
      </div>
      <div class="card-content collapse show" style="">
        <div class="card-body  text-center">
            
              <div class="avatar bg-rgba-danger p-50 m-0 mb-1">
                <div class="avatar-content">
                <img src="https://img.icons8.com/cotton/38/000000/hand-with-a-pill.png"/>
                </div>
              </div>
              <h2 class="text-bold-700">{{ $empleado->expediente->consultas->count() }}</h2>
              <p class="mb-0 line-ellipsis">Medicamentos Activos</p>
            
        </div>
        <div id="chart" style="min-height: 365px;">
        </div>
       
      </div>
     </div>
  </div>
</div>





{{-- @dd($empleado->expediente->consultas->count()) --}}

{{-- @foreach ($empleado->expediente->consultas as $consulta)
    @foreach($consulta->medicamentos as $medicamento)
            {{$medicamento->nombre}}<br>
    @endforeach
@endforeach --}}



@endsection


@section('page_vendor_js')

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/2.3.0/list.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="https://use.fontawesome.com/6571a6d6ab.js"></script>


@endsection
@section('page_js')
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script src=" {!! asset('public/vuexy/app-assets/js/scripts/modal/components-modal.min.js') !!} "></script>
<script src="{!! asset('public/vuexy/app-assets/js/scripts/extensions/sweet-alerts.min.js') !!}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
@endsection
@section('js_custom')

<script src="{!! asset('public/js/empresa/info_paciente.js') !!}"></script>
<script src="https://ac-labs.com.mx/asesores/app-assets2/vendors/js/charts/echarts/echarts.js"></script>
<script src="https://ac-labs.com.mx/asesores/app-assets2/vendors/js/charts/echarts/chart/bar.js"></script>
<script src="{!! asset('resources/js/charts-empleado.js') !!} "></script>
<script src="{!! asset('public/js/empresa/antecedente/antecedentes.js') !!}"></script>
<script src="{{ asset('public/js/empresa/empleado/medicamentos.js') }}"></script>

<script src="{!! asset('public/vuexy/app-assets/js/scripts/popover/popover.min.js') !!}" charset="utf-8"></script>
@endsection